export declare const BLOXMOVE_URL_V1 = "https://raw.githubusercontent.com/bloxmove-com/bloxmove-vocab/master/v1";
declare const BLOXMOVE_VOCAB: {
    "https://raw.githubusercontent.com/bloxmove-com/bloxmove-vocab/master/v1": {
        "@context": ({
            "@version": number;
            schema?: undefined;
            minAge18?: undefined;
            minAge21?: undefined;
            minAge25?: undefined;
            driverLicense?: undefined;
            company?: undefined;
            familyName?: undefined;
            givenName?: undefined;
            birthCountry?: undefined;
            birthDate?: undefined;
            age?: undefined;
            streetAddress?: undefined;
            postalCode?: undefined;
            country?: undefined;
            identifier?: undefined;
            validUntil?: undefined;
            issueDate?: undefined;
            issuerName?: undefined;
            vehicleDID?: undefined;
            rentalContractDID?: undefined;
            topic?: undefined;
        } | {
            schema: string;
            minAge18: string;
            minAge21: string;
            minAge25: string;
            driverLicense: string;
            company: string;
            familyName: string;
            givenName: string;
            birthCountry: string;
            birthDate: string;
            age: string;
            streetAddress: string;
            postalCode: string;
            country: string;
            identifier: string;
            validUntil: string;
            issueDate: string;
            issuerName: string;
            vehicleDID: string;
            rentalContractDID: string;
            topic: string;
            "@version"?: undefined;
        })[];
    };
};
export { BLOXMOVE_VOCAB };
