import { AssetService } from './asset.service';
import { ConfigService } from '../config/config.service';
import { IDataProperties, PermissionsEnum } from '../interfaces/interfaces';
import { VerifiableCredential } from '../classes/verifiable-credential.class';
import { DIDDocument } from 'did-resolver';
import { VerifiablePresentation } from '../classes/verifiable-presentation.class';
export declare class UniversalAssetService implements AssetService {
    private readonly loggerFormat;
    private readonly loggerOptions;
    private readonly logger;
    private readonly currentAccountDidMethod;
    private readonly assetServiceImplementations;
    private readonly assetHelperService;
    constructor(config: ConfigService);
    private getAssetServiceForDidMethod;
    private getDidMethod;
    private getAssetServiceForDid;
    init(): Promise<void>;
    createAsset(assetName: string, initialDataProperties: IDataProperties, assetType?: string, accountAddress?: string): Promise<string>;
    addInvolvedParties(assetDID: string, involvedPartiesDIDs: string[], permissions: PermissionsEnum[]): Promise<void>;
    getInvolvedParties(assetDID: string, permission: PermissionsEnum): Promise<string[]>;
    getDataProperty(assetDID: string, key: string, assetType?: string): Promise<string | null>;
    createDataProperty(assetDID: string, key: string, value: string, assetType?: string, changeable?: boolean): Promise<void>;
    getAttestations(assetDID: string, topic: string): Promise<Array<VerifiableCredential | string>>;
    resolveName(name: string): Promise<string | null>;
    setName(name: string, assetDID: string): Promise<void>;
    verifySignature(signerDID: string, message: string, signature: string): Promise<boolean>;
    getOwner(assetDID: string): Promise<string>;
    signMessage(message: string): Promise<string>;
    isValidDID(assetDID: string): Promise<boolean>;
    getDIDDocument(assetDID: string): Promise<DIDDocument>;
    setDIDDocument(didDocument: DIDDocument): Promise<void>;
    createVerifiableCredential(type: string[], credentialSubject: any, proofPurpose?: string, expirationDate?: string): Promise<VerifiableCredential | string>;
    createVerifiablePresentation(verifiableCredentials: Array<VerifiableCredential | string>, proofPurpose?: string, expirationDate?: string): Promise<VerifiablePresentation | string>;
    updateDataProperty(assetDID: string, key: string, value: string, assetType?: string): Promise<void>;
    setAttestation(assetDID: string, topic: string, vc: VerifiableCredential | string): Promise<void>;
    validateVerifiableCredential(verifiableCredential: VerifiableCredential | string): Promise<VerifiableCredential | undefined>;
    private extractPayloadFromJwtVc;
    validateVerifiablePresentation(expectedSignerDid: string, verifiablePresentation: VerifiablePresentation | string): Promise<VerifiableCredential[]>;
}
